src/builder.rs, src/lib.rs
I have not actually tested this yet. However, it compiles with `cargo build` and I believe the interface is correct.
I added a new API `remove` so that `delete` retains backwards compatibility.
=> add a container deletion api that takes options

src/transport.rs
I don't know what the benefit of having a panic here is. It caught me off-guard when I make an API request for a container that was already destroyed.
=> don't panic

README.md, src/rep.rs
Example in README couldn't compile. Compilation error : 
`PullOptions` is the name of a struct or struct variant, but this expression uses it like a function name [E0423]
&PullOptions.builder().image("redis:2.8.18").build()
=> Update README.md + Fix repr.rs on containerDetails (change in docker remote API)

src/rep.rs
"id" and "status" are not present in network events. At the future I might create a pull request that adds support for different types of events, but at the moment this patch prevents the library from panicking when receiving a network event.
=> Make id and status optional for events

src/transport.rs
It is currently impossible to create new container. This patch resolves this
issue. See the following link for details:
https://github.com/docker/docker/issues/20865
=> Set the Host header

src/errors.rs
Implementing the standard Error trait allow composing the library error together
with frameworks such as error-chain
=> Implement the standard Error trait

src/builder.rs
Attempting to address #34 
* adds a `params_hash` object to the `ContainerOptions` struct to track params that need to be serialized as arrays of objects
* adds a `devices` method to expose `params_hash` for adding "Devices"
In the current state creating a `device` would like like the following: 
```rust
let mut opts = ContainerOptions::builder("alpine:latest");
let mut devices = Vec::new();
let mut device = HashMap::new();
device.insert("PathOnHost".to_string(), "/dev/deviceName".to_string());
device.insert("PathInContainer".to_string(), "/dev/deviceName".to_string());
device.insert("CgroupPermissions".to_string(), "mrw".to_string());
devices.push(device);
opts.devices(devices);
let container_options = opts.build();
```
=> Add support for Devices

src/lib.rs, src/rep.rs
I came across this bug when trying to build an image which relies on a repository that doesn't exist locally. The Docker API replies with "status" messages for downloading/extracting the base image.
=> Fixed bug where `Images::build` panics on "status" replies

examples/export.rs, src/lib.rs, src/tarball.rs, src/transport.rs
Currently structures store a raw str slice, which makes for poor API ergonomics. By storing a `Cow<str>`, the struct can outlive the stack data if necessary.
I discovered the downside of the current API, which I queried here: https://users.rust-lang.org/t/binding-does-not-live-long-enough-even-though-its-being-returned/9002
Also, this is a good article on the topic, if you're interested: http://blog.jwilm.io/from-str-to-cow/
Btw, I also snuck in a commit to squash some warnings that were getting annoying!
=> Store Cow<str> instead of &str

Cargo.toml, src/lib.rs
Hi,
This PR updates the `hyper` crate to `v0.10` which removes the dependency to `openssl`. TLS support is added through the `hyper-openssl` crate.
This depends on https://github.com/softprops/hyperlocal/pull/5 which also updates `hyperlocal` to `v0.10` to avoid a clash with `openssl-sys` versions.
Some context here: https://github.com/hyperium/hyper/issues/985
Signed-off-by: Alexandre Beslic <abeslic@abronan.com>
=> update to hyper v0.10 with separate openssl dependency

src/lib.rs
Use shiplift with insecure docker remote API
=> [Docker Host] Support for non-https remote API

src/rep.rs
While using this library I needed one of the types to derive from `Clone`, so I made all of them clonable.
I'm fairly new to Rust, so let me know if this is not desired.
=> Make rep-types clonable

src/transport.rs
If the HTTP response contains a JSON object with a "message" member, this is extracted as the error message in place of the default string.
=> The transport extracts a message from the response JSON if possible

src/builder.rs
Note that this requires support for specifying non-string values in container options, since the maximum retry count is an integer.
=> Added support for setting a restart policy on a container

src/builder.rs
Expose the API value directly, instead of trying to mirror `build --network`'s behaviour. I am interested in the "network name" case, so any validation is impossible anyway.
=> support for --network= during build

Cargo.toml, src/lib.rs, src/transport.rs
And by making that optional, the hyperlocal dependency can be made optional as well (= hidden behind the "unix-socket" feature). And without the hyperlocal dependency, the project can be used on Windows; obviously only over HTTP(S).
=> Make Unix socket support optional

.gitignore, src/rep.rs
According to https://docs.docker.com/config/containers/resource_constraints/#--memory-swap-details, swap values may be -1
=> Allow memory swap to be negative

src/rep.rs
Searching images ends with an error:
```
Err(
Decoding(
MissingFieldError(
"is_trusted"
)
)
)
```
As far as I could check (Docker Engine API 1.18, now 1.37), I could not find the `is_trusted` field on the [search response](https://docs.docker.com/engine/api/v1.37/#operation/ImageSearch). In stead, there is an `is_automated` field, wich sounds similar. Anyway, it seems the API response payload has changed in a non-backward compatible fashion.
This PR replaces the old field with the new one, and search works fine again.
```rust
extern crate shiplift;
use shiplift::Docker;
let docker = Docker::new();
let images = docker.images();
let res = images.search("rust");
println!("{:#?}", res);
```
```
Err(
Decoding(
MissingFieldError(
"is_trusted"
)
)
)
```
```
Ok(
[
SearchResult {
description: …
```
=> Solution to the MissingFieldError problem on /images/search.

src/rep.rs
These appear to be around since Docker Engine API v1.22:
https://docs.docker.com/engine/api/v1.22/
Finding info on what Docker version had what API version is a bit tricky, but 1.22 seems to have been around since Docker 1.10 at the latest.
=> Add new event info fields (Type, Action, Actor) to Event

src/rep.rs
These fields don't seem to exist in any version of the API I can find. They certainly don't exist on my system (Docker 18.06).
Fixes #75.
=> Remove swap fields from MemoryStat

src/rep.rs
Apparently `Image.repoTags` can be `null`, so turn it into an `Option<Vec<String>>`
=> Image.RepoTags seems to be optional (can be null)

src/tty.rs
I had a case where I wanted to get output from both stdout and stderr but preserving the order, so I hacked up `Tty` to do that. It might be useful to someone else.
=> Add InterlacedTty

src/lib.rs
Use the `serde_json` api correctly for streams of data. (example in ticket)
Closes: #123
Works for my app: https://github.com/FauxFaux/fappa/commit/5ff21c38ef555f0ff5f5f0134fef6c8c175cf3d1#diff-639fbc4ef05b315af92b4d836c31b023R138
=> serde can't read a Vec<Value> from a stream

src/lib.rs
Thanks for the awesome crate! I was having some issues using with Docker for Windows (in combination with the Windows Subsystem for Linux) and this PR fixes that. Happy to make any adjustments that are required. 
This PR manually builds a `HttpConnector` from Hyper so that it does not fail if the protocol is not `http`. Therefore, `DOCKER_HOST` of the form `tcp://127.0.0.1:2375` will work with shiplift.
Closes: N/A
Tested with the project I'm working on where this was failing previously.
N/A
=> Disable Hyper's http protocol enforcement.

src/builder.rs, src/tty.rs
I've added support for `HostConfig.AutoRemove` parameter when creating new container.
1. I modified one of the unit tests to include this parameter.
2. I've tested if container is properly removed after execution using this snippet: 
```rust
use shiplift::{ContainerOptions, Docker};
use tokio::prelude::Future;
fn main() {
let docker = Docker::new();
let create_opts = ContainerOptions::builder("alpine:3.7")
.auto_remove(true)
.name("test")
.cmd(vec!["echo", "123"])
.build();
let create_fut = docker
.containers()
.create(&create_opts)
.map(move |info| {
println!("{:?}", info);
let start_fut = docker
.containers()
.get(info.id.as_ref()).start()
.map_err(|e| eprintln!("Error: {}", e));
tokio::spawn(start_fut);
})
.map_err(|e| eprintln!("Error: {}", e));
tokio::run(create_fut);
}
```
Added …
=> Support for AutoRemove flag

src/builder.rs, src/lib.rs, src/tty.rs
This removes an unused type parameter from the 'nocache' function
The function is currently unusable because the type parameter has no
uses or bounds.
Callers of the function must explicitly specify the type `R`, even though the specific type is meaningless.
I could successfully call `nocache` without type explicit type parameters with the patch.
=> Remove an unused type parameter from the 'nocache' function

src/builder.rs, src/tty.rs
This adds support for setting CPU shares and the memory limit when creating images and containers.
I used a the patch in a project so that it wouldn't take so long to rebuild an image I often rebuild.
* Support for setting allocation of CPU shares memory when creating images and containers has been added.
=> Support for setting CPU shares/memory for image builder

src/builder.rs
This adds new `ContainerOptionsBuilder` method `privileged()` to enable running privileged docker containers. I think it should be mentioned in CHANGELOG.md. Also, this could be potentially an incompatible change, since API addition is considered an incompatible change in semver universe.
The implementation is pretty straightforward, - the `privileged` field is already present in `HostConfig`, so there is only a new builder option to set the field to a required value.
As a side note - I have followed the precedence set by `auto_remove()` that gets a boolean argument. However, if I was to implement it from the scratch I'd choose to drop the boolean argument completely (similarly to the `docker` command line - you only mention it if you need it).
Fixes #148
=> Add ContainerOptionsBuilder::privileged()

Cargo.toml, examples/containercopyfrom.rs, src/builder.rs, src/lib.rs, src/rep.rs, src/transport.rs, src/tty.rs
Added `copy_from` to `Container` - this returns a `Stream` of `Vec<u8>`s (similar to `export`) the stream is actually a `Tarball` of the requested files (as you can see in the example).
I've also run `clippy`/`fmt`/`upgrade` over the codebase.
* Added `example/containercopyfrom`
* Nothing beyond the new function.
=> Copy from container

Cargo.toml, src/builder.rs, src/rep.rs, src/transport.rs
This is in line with best practices recommended by serde[[1]].
This will also resolve downstream crates depending on shiplift who enable the
serde derive feature, due to Cargos unification of features for each crate[[2]].
[1]: https://github.com/serde-rs/serde/issues/1441
[2]: https://github.com/rust-lang/cargo/issues/4361#issuecomment-348538243
Example of the problem for downstream crates:
```
$ cargo new deptest
$ cd deptest
$ echo 'shiplift = "0.4"' >> Cargo.toml
$ echo 'serde = { version = "1.0", features = ["derive"] }' >> Cargo.toml
$ cargo build
```
This will result in the following error:
```
error[E0252]: the name `Serialize` is defined multiple times
--> /home/veeg/.cargo/registry/src/github.com-1ecc6299db9ec823/shiplift-0.4.0/src/builder.rs:5:5
|
4 | use serde::Serialize;
| …
```
=> Migrate serde dependency to use derive feature

src/builder.rs
Closes: #161
I compared the results of creating a container via the command line and via shiplift (confirming that the ports column is populated correctly). I also curl'd against the REST API to retrieve the json from the running containers to compare before and after.
Added `ExposedPorts` mapping when creating a container.
=> Added `ExposedPorts` mapping

src/builder.rs
Added a documentation for the `volumes` option.
Closes: #163 
Generated documentation locally
=> Add explanative sentence for volumes option

src/builder.rs
`LogsOptionsBuilder::since()` method (according to [Docker Engine API](https://docs.docker.com/engine/api/v1.30/#operation/ContainerLogs))
Make tests for all `LogsOptionsBuilder` methods
=> Add LogsOptionsBuilder::since() method

examples/containercopyinto.rs, src/lib.rs
Made copy_file_into slightly more ergonomic by accepting `AsRef<Path>`
Ran example
copy_file_into method signature changed to accept any `AsRef<Path>`
=> Switch path type requirement to make more ergonomic

Cargo.toml
Switch to vendored openssl to ease building on windows.
=> Switch to vendored openssl

src/builder.rs
Closes: #174
I use the fork inside of my work project
Add WorkingDir container's option support
=> Add WorkingDir container's option support

src/lib.rs
The `copy_file_into` function required that the parent directory of the file to copy exists in the container. This PR ensures that the required path will be created automatically. 
Tested with the example `examples/containercopyinto.rs` and tested with [PREvant](https://github.com/aixigo/PREvant) by [this commit](https://github.com/aixigo/PREvant/pull/7/commits/4c7e25685219a0f3521be70267d893ab2e1c23f9).
=> copy_file_into creates sub-directories if required

rustfmt.toml
Closes: #xxx
rustfmt recently stabilized a rustfmt config option this project used and changed its name in the process. This change updates our usage to use that new name
ci
=> rustfmt config option name changed

CHANGELOG.md, Cargo.toml, examples/images.rs, src/builder.rs, src/rep.rs
Add chrono as a feature to deserialize date times 
Closes: #186 
Tested with all examples and uni tests
=> feat: use chrono to deserialize date times

src/errors.rs, src/lib.rs, src/tty.rs
->  I found that trait objects without an explicit dyn are deprecated - https://travis-ci.org/softprops/shiplift/jobs/580271710, and I followed the suggestion given by the compiler to fix this.
Closes: #xxx
=> Use 'dyn' since trait objects without an explicit 'dyn' are deprecated

examples/volumes.rs
-> Fix `cargo fmt` build failure - https://travis-ci.org/softprops/shiplift/builds/585217932
Closes: #xxx
-> by checking the build logs for this PR.
-> nothing.
=> Remove extra semicolon to fix cargo fmt --all -- --check

src/rep.rs
The `endpoint_id` field is stylized as `EndpointID` in the Docker API when returning container-details for a network ([1]).
[1]: https://docs.docker.com/engine/api/v1.24/#35-networks
When previously I called `.inspect` on a Docker network, it failed with the (Serde) error:
```
missing field `EndpointId`
```
After changing the rename-definition of the `endpoint_id` field in `NetworkContainerDetails` it now works correctly.
=> Correctly rename `endpoint_id` field

Cargo.toml, src/builder.rs
```
ContainerOptionsBuilder::publish();
```
I added the publish function to only expose port on the container instead of mapping ports.
I got an automated nginx_proxy (https://github.com/jwilder/nginx-proxy) that'll detect automatically if a container is added to his network and for that, you only need to expose ports of the container with a `docker run --expose 5000 something` and if multiples, specify it with env variables
But with shiplift, I couldn't only expose a port, I had to do the mapping.
By testing and with units tests.
publish method added to publish container's ports.
=> Add 'publish' method to expose a port

examples/volumes.rs, src/builder.rs, src/lib.rs
During our testing in https://github.com/timberio/vector/pull/787 we found that there is an issue with hyper connecting to a tls connected docker engine that provided a host url of `tcp://...`. I found the way to fix this was to replace the `tcp` scheme with `https`. This seems to work for when encrypted `tcp` streams are active. The error hyper produces was a version parse error which seemed odd. This seemed to do the trick.
Related to #192
=> Replace host str to use https if encrypted

Cargo.toml, src/transport.rs
This relates to #170 where shiplift switched to using vendored openssl to assist windows builds.  Unfortunately I believe that change went too far the other way, using the system-wide OpenSSL is much more common on *nix systems, and the vendoring gets in the way of other tooling (e.g. building an RPM from such a binary leads to problems, as the RPM will try to "depend" on the vendored shared object, which will not be resolvable from the repo).
This change enables the `vendored` feature only on windows builds, and reverts to the default behaviour (searching for a system-wide version using pkg-config if present) on other systems (mac, linux...)
I considered an alternative option, that of exposing a `vendored-ssl` feature that enables the `openssl/vendored` feature, which can be enabled if …
=> Don't vendor OpenSSL except on Windows

README.md, examples/custom_host.rs
The example in the README is outdated and no longer compiles. To prevent this from happening again, this patch removes the example entirely and instead introduces a new example `custom_host` that will be checked during `cargo test`.
Closes: #183.
-
-
=> Replace invalid example in README with cargo example

src/rep.rs
Add missing fields to `rep::Container`:
- `image_id` (`ImageID`, API version 1.21)
- `state` (`State`, API version 1.23)
`cargo test`
=> Expand rep::Container fields

examples/version.rs, src/rep.rs
Expand `shiplift::rep::Version` to contain fields for the following
elements of the `/version` API:
- `os` (`Os`, API version 1.18*)
- `arch` (`Arch`, API version 1.18*)
- `kernel_version` (`KernelVersion`, API version 1.18*)
- `build_time` (`BuildTime`, API version 1.22)
(* API version 1.18 is the oldest currently-published API version, fields may in fact be older.)
Add a new example program to display version information.
`cargo test`
=> Expand rep::Version

src/builder.rs
The following change is to provide the configuration option
`PublishAllPorts` which will map all exposed ports on a container to
random and available ports on the host machine.
This configuration option is documented
[here](https://docs.docker.com/engine/api/v1.39/#operation/ContainerCreate).
CHANGELOG.md is not updated, because I do not think there are any breaking changes.
Closes: https://github.com/softprops/shiplift/issues/214
I have added a test to the builder; builder::tests::container_options_publish_all_ports
Ran cargo test with the following results.
```
running 12 tests
test builder::tests::container_options_publish_all_ports ... ok
test builder::tests::container_options_nested ... ok
test builder::tests::container_options_host_config ... ok
test …
```
=> Update the ContainerOptionsBuilder with new publish all ports option

Cargo.toml, src/errors.rs, src/lib.rs, src/transport.rs, tests/reexported_types.rs
This patch removes the explicit dependency on the http crate and instead accesses the re-exported version of hyper. This should make the update process slightly easier because those versions would need to be kept in sync manually.
We also re-export hyper::Uri as shiplift::Uri because it is part of the public API of shiplift::Docker. This allows users to access the Uri type without having to seperately depend on http or hyper.
I added a test that makes sure we can access the re-exported type.
`http::Uri` is now explicitly re-exported to allow downstream users to access it without adding a dependency on http themselves.
=> Re-export hyper::Uri as shiplift::Uri

src/builder.rs
`builder::ContainerListOptionsBuilder::all()` takes no arguments, assuming a true
value. However, `builder::ImageListOptionsBuilder::all()` accepts a boolean.
To make these consistent, the latter no longer accepts a boolean and,
like the former, assumes true.
`cargo test`
`shiplift::builder::ImageListOptionsBuilder::all()` no longer accepts an argument and always sets the option to true.
=> Make image and container option builder interfaces consistent

src/builder.rs
Ran `cargo +nightly fmt --all` as indicated in the PR template. Since this affects code not otherwise being modified, I did this as a separate PR.
=> Fix formatting

src/errors.rs
Update the internal `Error` type to the latest `std::error::Error` trait:
- `description` is deprecated, and with the 1.42 stable release it is now generating warnings
- `cause` is deprecated and replaced with `source`
`cargo test`
=> Update errors to match current std::error::Error trait

src/rep.rs
Added `repo_tags`, `repo_digests` to `ImageDetails`. Added in version [1.21](https://docs.docker.com/engine/api/v1.21/) of the Docker API.
`cargo test`, manual testing.
=> Add repo_tags, repo_digests fields to ImageDetails

src/builder.rs
A User can now be specified when creating a container, per https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate
Ran tests, and tested locally.
Nothing.
=> Specify user when creating container

src/builder.rs
I added `nano_cpus` and `memory_swap` methods to `ContainerOptionsBuilder` corresponding to the options here https://docs.docker.com/engine/api/v1.40/#operation/ContainerCreate
No related issues.
`cargo clippy`, `cargo fmt`, `cargo test`, and I integrated this branch successfully into my project.
`ContainerOptionsBuilder` now supports setting "MemorySwap" and "NanoCPUs" options of container creation endpoint.
=> Add nano_cpus and memory_swap to ContainerOptions

src/transport.rs
This simply removes the the restriction for streaming on UNIX domain sockets. It works for my use cases and I haven't found any documentation that the mechanism differs from streaming over TCP.
Closes: #166
Using `container.attach()` over a local docker instance without TCP enabled.
*nothing*
=> Enable streaming results over UNIX sockets

src/lib.rs
Added a `Container::copy_to` method which allows uploading a pre-existing tarball to the container.
Calling the new method with an archive generated by the `tar` crate.
*nothing*
=> Implement upload of tar to container

src/builder.rs
This type signature makes it impossible to dynamically construct a
`Vec<String>` of environment variables and pass it to the builder.
This patch tries to fix that by making the function only take a
reference to a slice containing the environments.
Added a test.
`ContainerOptionsBuilder::env()` signature changed
---
Please take this as a proposal. It is most certainly not the nicest solution for the problem described above.
=> ContainerOptionsBuilder::env() should not get owned Vec

src/lib.rs, src/transport.rs
Move logic from `Image::build` for converting a stream of chunks into a stream of values to a new `stream_post_into_values` function, and use that in `Image::pull`.
This fixes a bug on WSL2 where shiplift errors when calling `Image::pull` on an image that has already been pulled. In this case the response from the docker daemon contains two JSON values in a single chunk.
Successfully ran the image pull example twice in succession with the same argument.
Nothing.
=> Allow `Image::pull` to handle chunks with multiple JSON values

src/builder.rs
Current implementation of `RegistryAuth` doesn't work, because it should be encoded in url_safe base64 variant.
Relevant docs: https://docs.docker.com/engine/api/v1.41/#section/Authentication
=> Fix X-Registry-Auth header

Cargo.toml, src/lib.rs, src/transport.rs, src/tty.rs
This pull request upgrades all dependencies to their latest version and fix incompatible code. Specifically, this updates tokio from 0.2 to 1.0, which makes shiplift usable in newer projects.
* Changed version strings in Cargo.toml.
* Implemented a special case for `unix:///` URLs, since `"unix:///var/run/docker.sock".parse::<hyper::Uri>()` will now return an error saying the authority can't be empty.
* Created unit test for this special case.
* For some reason there is an empty `/lib.rs`. This pull request also removed it.
* `cargo test --no-default-features` pass
* `cargo test` pass
* Tried `cargo run --example info` with `DOCKER_HOST` set to `unix:///...`, `http://...` and `tcp://...` URLs.
* Verified that creating containers, starting and attaching to them still works, since I'm using …
=> Upgrade all dependencies

CHANGELOG.md, src/builder.rs
I added options to set the `StopSignal` and `StopTimeout` options in [`/container/create`](https://docs.docker.com/engine/api/v1.40/#operation/ContainerCreate).
Since StopSignal can be either a string or a number, I added methods for both. I thought about using [`nix::sys::signal::Signal`](https://docs.rs/nix/0.19.1/nix/sys/signal/enum.Signal.html) but it seemed unnecessary to bring in the entire library for a single enum.
I tested this manually on my codie-discord project which uses shiplift.
The changelog was updated in this PR.
* add StopSignal and StopTimeout to ContainerOptionsBuilder [#248](https://github.com/softprops/shiplift/pull/248)
=> Add StopSignal and StopTimeout to ContainerOptionsBuilder

src/lib.rs
I made the argument of Image::import generic so that it's nicer to call.
Closes: #249
Tested example `import` that uses this method and confirmed that it correctly import images from a tarball.
It doesn't seem to be a breaking change or anything. Perhaps a note that this function is now generic over `Read + Send + 'a`
=> Image::import argument tarball is now generic

examples/execinspect.rs, examples/execresize.rs, src/builder.rs, src/lib.rs, src/rep.rs
This PR adds possibility for a user of this crate to manipulate Exec instances through newly added Exec struct. Main motivation was to be able to check the exit_code of a given exec after its completion or to check its status while it's still running (inspect it). It also allows users to create execs without the need to start them immediately.
Any suggestions on how to handle it better, or to change naming are welcome.
Closes: #219
Briefly tested locally on one or two instances.
A new Exec struct was introduced that allows dynamically creating exec instances, manipulating them and inspecting their status.
=> Add Exec struct for easier manipulation of exec instances

examples/attach.rs, examples/logs.rs, src/lib.rs
It's an initial attempt at making the api easier and more approachable. This PR gets rid of unnecessary lifetimes in structs and makes them own at least their id/name.
I'll leave this empty for now and fill this out when this PR will be ready.
=> Simplify api, get rid of unnecessary lifetimes

CHANGELOG.md, examples/attach.rs, examples/containerlogs.rs, examples/export.rs, examples/imagebuild.rs, examples/networkdisconnect.rs, examples/servicelogs.rs, examples/volumecreate.rs, examples/volumedelete.rs, examples/volumes.rs, src/lib.rs, src/transport.rs, src/tty.rs
After a dance with borrowck, I updated the lifetimes of problematic methods in `lib.rs` where the return's lifetime was unnecessarily tied to some of the inputs. In particular, `{Containers, Images, Networks, Services, Volumes}::get()` now return a `{Container, Image, Network, Service, Volume}` which is tied to the lifetime of the `Docker` they container rather than the lifetime of the `{Containers, ...}` which created them. This means we no longer have to create unnecessary locals such as `images` in the following code to avoid the compiler complaining about `temporary value dropped while borrowed`
```rust
let images = docker.images();
let mut stream = images.build(&options);
```
Instead, we can write the following as you would intuitively expect to work.
```rust
let mut stream = …
```
=> Fix lifetimes

src/lib.rs
Documentation missing on `Containers::get()` was added.
Part of: #275
Nothing
=> Add warning to Containers::get() method

src/lib.rs
Containers::get() does always return a handle to a container, which might be invalid.
This function checks whether the container exists before returning either a Some(Container) or None.
Part of: #275
New function `Containers::get_checked()`
=> Add Containers::get_checked() for getting an existing container

CHANGELOG.md, src/network.rs
Added missing fields to NetEntry, namely Links, Aliases and IPAMConfig.
Closes: #227
Tested locally and got expected results:
```
❯ cargo run --example containerinspect -- f74a8ceb19a9
Blocking waiting for file lock on build directory
Compiling shiplift v0.7.0 (/home/wojtek/dev/shiplift)
Finished dev [unoptimized + debuginfo] target(s) in 5.42s
Running `target/debug/examples/containerinspect f74a8ceb19a9`
ContainerDetails {
app_armor_profile: "",
args: [
"10000",
],
config: Config {
attach_stderr: true,
attach_stdin: true,
attach_stdout: true,
cmd: Some(
[
"sleep",
"10000",
],
),
domainname: "",
entrypoint: None,
env: Some(
[
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
],
),
exposed_ports: None,
hostname: "f74a8ceb19a9",
...
network_settings: NetworkSettings { …
```
=> Add missing fields to NetworkEntry

rustfmt.toml
```shell
$ cargo +nightly fmt --all -- --check
```
=> Replace deprecated option `merge_imports` for rustfmt

src/errors.rs
Small change to the `Display` implementation of `Error` that includes the `message` returned by docker.
IMO this should be part of the display string since it makes errors much more informative.
E.g., instead of `Docker Error: 404 Not Found` an error would now be displayed as `Docker Error: 404 Not Found: No such container: containername`
Closes: https://github.com/softprops/shiplift/issues/288
manually tested it on one API request 😄
include additional information in error messages
=> Display error message for `Error::Fault`

src/container.rs, src/lib.rs, src/network.rs
When testing my [previous PR](https://github.com/softprops/shiplift/pull/280), I noticed a change that must have come after 0.7.0: At first glance, it looked like the `NetworkInfo` returned by `Networks::list()` lost a lot of the props that it had before.
After some digging in the history I think I found the problem:
`network.rs` [used to import](https://github.com/softprops/shiplift/blob/a871f1df049356d035da196676125f3585912f49/src/network.rs#L17) `rep::NetworkDetails` as `NetworkInfo`. After the latest refactoring however, it looks like there is [*another*](https://github.com/softprops/shiplift/blob/3667ae716733b26526f6c16d8312bc22129430d6/src/network.rs#L340-L350) `network::NetworkInfo`, which is part of the `Stats` struct returned by `container::stats()`.
Some more digging reveals …
=> Fix incorrect return type of Networks::list

src/container.rs
Hi! :wave:
Fixed a problem with `ContainerListOptionsBuilder`, where it was not possible to use multiple filters of the same type.
For example, the following only matches agains the `second` label; the `first` label is dropped:
```rust
// expected to behave like --filter "label=first=value1,second=value2"
// actually behaves like --filter "label=second=value2"
let opts = ContainerListOptions::builder()
.filter(vec![
Label("first".to_string(), "value1".to_string()),
Label("second".to_string(), "value2".to_string()),
])
.build();
```
While at it, I noticed that `ExitCode(_)` is serialized to `exit` whereas the [documentation](https://docs.docker.com/engine/api/v1.41/#operation/ContainerList) expects `exited`.
To verify the serialization of the labels and filters, I added some tests and ran …
=> Allow multiple filters of same type and fix ExitCode filter name

src/container.rs
I have found this bug because my software crashed. I applied this patch to shiplift, rebuilt my software, it did not crash anymore but report the error appropriately.
---
There are more `unwrap()` calls in the codebase which we might want to remove soonish. I'll open an issue for that.
=> Fix unwrap: Return error instead of crashing

src/image.rs
Port from #261 minus changelog updates, which will be submitted seperately.
=> Add `latest` tag by default to `PullOptionsBuilder`
