- src/builder.rs
Now we can create container with :
* volumes : bind host files/folders to this container
* volumes_from :  bind containers volumes to this container
* links : add links to the container
* network_mode : add a network mode
* extra_hosts : add a name to an ip
* env : add environements variables
* command : list of commands
* entrypoint : one entrypoint
> [ContainerOptions] add more options for container creation

- Cargo.toml
- src/lib.rs
- src/transport.rs
This seems to work with a Unix socket. I have not tested this with HTTP as I don't have such setup available at the moment. If you do not have such setup yourself then I'll please tell me and I'll create one for testing.
> Update hyper to 0.9 (fix #13)

- examples/containerexec.rs
- src/builder.rs
- src/lib.rs
Exec command for containers (#35)
> Exec container

- src/builder.rs
The log driver setting has a 3-level nested structure (`HostConfig.LogConfig.Type`) so I implemented a recursive function for mapping key names to JSON to replace the old special case for `HostConfig`.
> Add support for setting the log driver for a container

- Cargo.toml
- examples/containerexec.rs
- src/builder.rs
- src/lib.rs
- src/tty.rs
Pull request for #50
I choose to create a Tty object which contains stdout and stderr Strings.
I think very big output can be problematic. 
Is it good for you ?
> [ExecContainer] exec can now return stdout and stderr #50

- src/lib.rs
- src/rep.rs
Closes https://github.com/softprops/shiplift/issues/65
> Return RustcSerialize types instead of local types

- Cargo.toml
- src/builder.rs
- src/lib.rs
- src/rep.rs
Related to https://github.com/softprops/shiplift/issues/67
> Fix: Filter on multiples events of the same type

- src/rep.rs
> Add details entries for container networks

- .github/PULL_REQUEST_TEMPLATE.md
just the basics. cargo format enforcement is a separate issue https://github.com/softprops/shiplift/issues/106
fixes: https://github.com/softprops/shiplift/issues/105
> first pass at a pr template

- .travis.yml
- CONTRIBUTING.md
- examples/containers.rs
- examples/logs.rs
- examples/networkcreate.rs
- examples/networks.rs
- rustfmt.toml
- src/builder.rs
- src/errors.rs
- src/lib.rs
- src/rep.rs
- src/tarball.rs
- src/transport.rs
- src/tty.rs
Closes: #106
added ci checks for codestyle and ensure they passed
> try to get a consistent and repeatable codestyle going

- src/lib.rs
A few methods used some lifetimes that were too restrictive, so relax them.
Closes: #64
The tests still pass
> Fix some lifetime issues

- .travis.yml
Closes: #119
travis build ( after this is merged )
> only build _pushes_ to master

- .travis.yml
> conservative travis build cache

- examples/networkconnect.rs
- examples/networkdelete.rs
- examples/networkdisconnect.rs
- src/builder.rs
- src/errors.rs
- src/lib.rs
- src/rep.rs
- src/transport.rs
fix a number of clippy warnings. not all but most
> fix a number of clippy warnings

- .travis.yml
> update codecov tooling

- src/lib.rs
Fixes the 2nd part of #123 
Finding that 2nd part of #123 isn't broken now.
Nothing, just a hot-patch.
> Fixed error causing bad json to be sent to Docker API.

- CHANGELOG.md
- src/builder.rs
Closes: #115
build and test
added in this pull
> remove pub builder constructors

- src/builder.rs
- src/lib.rs
- src/rep.rs
```rust
ContainerOptionsBuilder::expose();
```
It adds the ability to expose ports from Containers.
Closes: #73 
Replaces: #74 
By testing and with units tests.
Nothing.
> [OK] Expose port

- examples/volumecreate.rs
- examples/volumedelete.rs
- examples/volumes.rs
- src/builder.rs
- src/lib.rs
- src/rep.rs
- src/tty.rs
Adds interface to create, list, and delete Docker volumes.
> feat: create, list, and delete volumes

- examples/networkconnect.rs
- examples/networkdisconnect.rs
- src/builder.rs
- Fixes serialization of network commands
- Adds `ContainerConnectionOptionsBuilder`
> Container Network Aliases

- .travis.yml
- CONTRIBUTING.md
- src/builder.rs
- src/errors.rs
- src/lib.rs
- src/tarball.rs
- src/transport.rs
- src/tty.rs
updated travis build and ran `cargo +nightly fmt --all`
Closes: #xxx
> update travis build

- src/errors.rs
fill in error description, delegating where possible 
Closes: #xxx
> fill in error details

- src/builder.rs
This PR adds support for `HostConfig.UsernsMode`.
> Support for Userns Mode

- examples/containercopyinto.rs
- src/lib.rs
- add function copy_file_into to container
- add example
> Copy a file into container

- src/lib.rs
When pulling images, sometimes multiple messages arrive in one chunk leading to errors about "trailing characters" (pointed out in https://github.com/softprops/shiplift/issues/143#issuecomment-450346853):
```
Error: Docker Error: trailing characters at line 2 column 1
```
This adds support for multiple messages per chunk, so that they are returned as if they arrived one at a time.
Using the `imagepull` example with Docker Engine 18.09.0 (Docker for Mac).
Before:
```
$ cargo run --example imagepull ubuntu:18.04
Finished dev [unoptimized + debuginfo] target(s) in 0.33s
Running `target/debug/examples/imagepull 'ubuntu:18.04'`
Object({"id": String("18.04"), "status": String("Pulling from library/ubuntu")})
Error: Docker Error: trailing characters at line 2 column 1
```
After:
```
$ cargo run …
```
> Support multiple messages per chunk in streaming image pull

- examples/containercopyinto.rs
- src/lib.rs
Due to my PR #151 the build was failing. This PR fixes the build.
> Apply rust format to fix CI checks

- Cargo.toml
- examples/imagepull_auth.rs
- src/builder.rs
- src/lib.rs
- src/transport.rs
Closes: #80 
I tested with gitlab private repo.
> Add a registry authentication.

- examples/import.rs
- src/lib.rs
Ability to import images
Closes: #7
Used the example to import images locally.
Addition of import method.
> Add import functionality

- src/lib.rs
Closes: #176
I'm using the fork in my work project, also it can be checked with the `examples/imagebuild.rs`
> Fix build image response parsing error

- examples/imagetag.rs
- src/builder.rs
- src/lib.rs
Added `tag` to `Image`.
I've also run clippy/fmt
- Added example/imagetag
> Added function to tag an image

- Cargo.toml
with a new release coming up, its a good time to upgrade deps. This pull just updates the minor, easy to update ones. 
Closes: #xxx
ci
> update minor deps

- .github/workflows/main.yml
- Cargo.toml
- README.md
- src/builder.rs
Ports build to GitHub actions. It has anecdotally provides a bit more in the way of putting my projects on auto pilot.
Closes: #xxx
> port build to gh actions

- CHANGELOG.md
- Cargo.toml
- README.md
> prep release for 0.6.0

- src/builder.rs
- src/lib.rs
Fix clippy's complaints.
`cargo test`, manual testing
> appease clippy

- src/rep.rs
Added the `status` field to the container `State` struct. This was added in version [1.21](https://docs.docker.com/engine/api/v1.21/) of the Docker API.
`cargo test`, manual testing
> Add status field to container State

- src/lib.rs
Streaming data in build function for images was no longer supporting multiple chunks, and thus intermittently fails with a Serde JSON parsing error, as described in #143. This PR fixes that for the async/await syntax support.
Run the imageebuild example specifying the path of a Dockerfile:
```shell
cargo run --example imagebuild <path>
```
Running this before this PR reveals the Serde JSON error, and running it after this PR shows that the errors are no longer emitting.
- Re-add support for multiple chunks
> Implement multiple chunk streams in build function for images

- CHANGELOG.md
- Cargo.toml
- README.md
Housekeeping help for next release, per https://github.com/softprops/shiplift/issues/235#issuecomment-762417706
> Version and changelog updates for 0.7.0

- Cargo.toml
> Update dependency: byteorder

- src/errors.rs
- src/lib.rs
- src/network.rs
This PR fixes CI by adhering to clippy lints that pop up in other PRs.
> Fix clippy lints

- src/container.rs
- src/exec.rs
- src/image.rs
- src/network.rs
- src/service.rs
- src/volume.rs
> Add Docker API reference hyperlinks to doc comments

- src/volume.rs
Added `Driver` and `DriverOpts` support [according to the Docker API](https://docs.docker.com/engine/api/v1.41/#operation/VolumeCreate).
Two tests were added to verify the proper serialization of the added options.
> Added volume driver support

- src/docker.rs
- src/image.rs
Port from #262 minus changelog updates, which will be submitted seperately.
> Image pull chunked

- src/container.rs
- src/image.rs
- src/lib.rs
Port from #266 minus changelog updates, which will be submitted seperately.
> Container details

- CHANGELOG.md
- README.md
Changelog updates from 
to reduce potential for merge conflicts in these PRs.
> Changelog updates
